name: Build FadiLabs Workflow

on:
  workflow_call:
    outputs:
      run-id:
        description: "Build workflow Run Id"
        value: ${{ jobs.build.outputs.run-id }}
        
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WEB_PROJECT_PATH: src/Web/Web.Server/Web.Server.csproj
      WEB_PUBLISH_OUTPUT: ./publish

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore Dependencies
        run: dotnet restore ${{ env.WEB_PROJECT_PATH }}

      - name: Build with dotnet
        run: dotnet build ${{ env.WEB_PROJECT_PATH }} --no-restore --configuration Release

      - name: Install EF Tool
        run: |
          dotnet tool install dotnet-ef

      - name: Generate migration scripts
        run: |
          dotnet ef migrations script -i -c UserContext -p ${{ env.WEB_PROJECT_PATH }} -o ./MigrationsScripts/UserContext.sql
          dotnet ef migrations script -i -c BlogContext -p ${{ env.WEB_PROJECT_PATH }} -o ./MigrationsScripts/BlogContext.sql

      - name: Upload migration scripts
        uses: actions/upload-artifact@v4
        with:
          name: fadilabs-web-migration-artifact
          path: ./MigrationsScripts
          if-no-files-found: error

      - name: Publish Artifact
        run: dotnet publish ${{ env.WEB_PROJECT_PATH }} --no-restore -c Release -o ${{ env.WEB_PUBLISH_OUTPUT }}

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: fadilabs-web-artifact
          path: ${{ env.WEB_PUBLISH_OUTPUT }}

    outputs:
      run-id: ${{ github.run_id }}