name: Deploy Fadilabs Server

on:
  workflow_dispatch:

jobs:
  call-build-workflow:
    uses: fadiksho/FadiLabs/.github/workflows/build-web.yml@main

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: fadilabs-web-artifact
          path: ./artifact/fadilabs-web-artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fadilabs'
          slot-name: 'Production'
          package: ./artifact/fadilabs-web-artifact