name: Deploy Server

on:
  workflow_dispatch:

jobs:
  build-web:
    uses: ./.github/workflows/build-web.yml

  deploy-web:
    runs-on: ubuntu-latest
    needs: build-web
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download fadilabs-web-artifact
        uses: actions/download-artifact@v4
        with:
          name: fadilabs-web-artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ needs.build-web.outputs.run-id }}
          path: ./artifact/fadilabs-web-artifact

      - name: Download fadilabs-web-migration-artifact
        uses: actions/download-artifact@v4
        with:
          name: fadilabs-web-migration-artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ needs.build-web.outputs.run-id }}
          path: ./artifact/fadilabs-web-migration-artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './artifact/fadilabs-web-migration-artifact/BlogContext.sql'
      - uses: azure/sql-action@v2.2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './artifact/fadilabs-web-migration-artifact/UserContext.sql'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fadilabs'
          slot-name: 'Production'
          package: ./artifact/fadilabs-web-artifact
