name: Deploy Fadilabs Server

on:
  workflow_dispatch:

jobs:
  build-web:
    uses: ./.github/workflows/build-web.yml@main

  deploy-web:
    runs-on: ubuntu-latest
    needs: build-web
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: fadilabs-web-artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ needs.build-web.outputs.run-id }}
          path: ./artifact/fadilabs-web-artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fadilabs'
          slot-name: 'Production'
          package: ./artifact/fadilabs-web-artifact
