name: Deploy Fadilabs Server

on:
  repository_dispatch: 
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.client_payload.run_id }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fadilabs'
          slot-name: 'Production'
          package: ${{ github.workspace }}/.net-app

          